import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  roomId: null,
  status: "idle",
};

export const appSlice = createSlice({
  name: "counter",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    enterRoom: (state, action) => {
      state.roomId = action.payload.roomId;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const { enterRoom } = appSlice.actions;

export const selectRoomId = state => state.counter.roomId;

export default appSlice.reducer;
